---
title: "Harmonic _Oscillator_Slice"
author: A. Mehta, A. Cheekoti, A. Tayade
output: html_notebook
---

Chunk 1: Defining global parameters.
```{r}
rm(list=ls())
N_dim = 1                         # Number of dimensions, only possible value 1

alpha_inc = 0.1                  # Incrememnt in alpha values
num_alphas=10                     # Total number of alphas 

num_walkers=100                    # Number of walkers
num_steps=10000                   # Number of total steps by each walker (thermalisation + sampling)
therm_steps=0.2*num_steps         # Number of thermalisation steps

slice_step = 01
```

Chunk 2: Defining functions for sampling and local energy.
```{r}
rho <- function(x,alpha) {
  return (sqrt(alpha)*exp(-2*alpha*(x^2)))
}

# Function to calculate local energy
elocal <- function(x,alpha) {
  return (alpha + (x^2)*(0.5-(2*(alpha^2))))
}

slice_x <- function(x,alpha,slice_step){
        x_new = x
        const = runif( 1 ,0, rho(x_new,alpha) )

        #Here end1 is the lower limit and end2 is the upper limit
        in_step_end1=runif(1,0,slice_step)
        
        end1 = x_new = x-in_step_end1
        while (const < rho(x_new,alpha) ) {
              end1 = x_new = x_new - slice_step
            }    

        end2 =  x_new = x+(slice_step-in_step_end1)
        while ( const < rho(x_new,alpha) ) {
              end2 = x_new = x_new + slice_step
              
            }
  
        x_new=point_new = runif(1,end1,end2)
        
        while(const > rho(x_new,alpha)){
              if ( point_new < x ) {
                    end1 = point_new
                  } else{end2 = point_new}

        x_new = point_new = runif(1,end1,end2)
        
        }
 
      return(point_new)
}
```

Chunk 3: Executing variational monte carlo with calculation of local energy and variance.
```{r}
alpha = 0.1                       # Initial value of alpha (variable parameter)
x_total=c()
E_local_sum_all = c()
E_local_sqd_sum_all = c()

alpha_all = c()

for (i in seq(num_alphas)){ #For different alphas
  
  E_local_sum_one_alpha = 0
  E_local_sqd_sum_one_alpha = 0
  alpha_all = c(alpha_all,alpha)
  
  for (j in seq(num_walkers))
    {
        x_sample=c()
        x= runif(N_dim,-2,2)            # Initial position of the walker
        
        for(k in seq(num_steps))   # Generate position values for each alpha
             { 
          
              x_dum=slice_x(x,alpha,slice_step)
              x_sample=c(x_sample,x_dum)
              x=x_dum
      
         } #one walker
        E_local_one_walker = elocal(x_sample[(therm_steps+1):num_steps],alpha)    # E_local_all for one particular alpha, all x
        E_local_sum_one_alpha = E_local_sum_one_alpha + sum(E_local_one_walker)   # Adding all local energy for all x, all walkers
    
        E_local_sqd_sum_one_alpha = E_local_sqd_sum_one_alpha + sum(E_local_one_walker * E_local_one_walker)
    
    
    }#one alpha  
  
  E_local_sum_all= c(E_local_sum_all,E_local_sum_one_alpha)  #array containing elocal for different alphas
  E_local_sqd_sum_all = c(E_local_sqd_sum_all,E_local_sqd_sum_one_alpha) #array containing elocal^2 for diff. alphas
  
  cat(i, "of", num_alphas, "alphas calculated.","\n")
  alpha = alpha + alpha_inc
}

E_local_var = E_local_sqd_sum_all/(num_walkers*(num_steps-therm_steps)) - (E_local_sum_all/(num_walkers*(num_steps-therm_steps)))^2

E_local_all = E_local_sum_all/(num_walkers*(num_steps-therm_steps))
std_dev = sqrt(E_local_var)
error = std_dev/sqrt(num_walkers*(num_steps-therm_steps))
```

Chunk 4: Main plots of our analysis.
```{r}
plot(alpha_all,E_local_var,xlab="alpha",ylab="Variance", main = "Variance vs alpha")

plot(alpha_all,E_local_all,xlab="alpha", ylab="Local Energy",ylim=range(c(E_local_all-error, E_local_all+error)), main = "Local energy vs alpha")
arrows(alpha_all, E_local_all-error, alpha_all, E_local_all+error , length=0.02, angle=90, code=3)
```




